# Generated by Django 5.2.5 on 2025-01-27 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Add the missing user field if it doesn't exist
        migrations.AddField(
            model_name='exam',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='exams', 
                to=settings.AUTH_USER_MODEL,
                null=True  # Allow null temporarily
            ),
        ),
        
        # Change exam_time to DateField if it's not already
        migrations.AlterField(
            model_name='exam',
            name='exam_time',
            field=models.DateField(verbose_name='Exam Date'),
        ),
        
        # Add the participants many-to-many field if it doesn't exist
        migrations.AddField(
            model_name='exam',
            name='participants',
            field=models.ManyToManyField(
                blank=True, 
                related_name='joined_exams', 
                to=settings.AUTH_USER_MODEL, 
                verbose_name='Participants'
            ),
        ),
    ]
