# Generated by Django 5.2.5 on 2025-09-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.TextField(default='', verbose_name='考试描述'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='category',
            field=models.CharField(default='Language', max_length=100, verbose_name='考试类别'),
        ),
        migrations.AddField(
            model_name='exam',
            name='difficulty',
            field=models.CharField(default='Beginner', max_length=20, verbose_name='难度'),
        ),
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.CharField(blank=True, max_length=50, verbose_name='考试时长'),
        ),
        migrations.AddField(
            model_name='exam',
            name='study_time',
            field=models.CharField(blank=True, max_length=50, verbose_name='建议学习时间'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='summary',
            field=models.TextField(verbose_name='考试内容概要'),
        ),
    ]