# Generated by Django 5.2.5 on 2025-09-07 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_updates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='study_time',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='summary',
        ),
    ]