# Generated by Django 5.2.5 on 2025-01-27 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_default_user_for_exams(apps, schema_editor):
    """为现有的exam记录设置默认用户"""
    Exam = apps.get_model('exams', 'Exam')
    User = apps.get_model('accounts', 'User')
    
    # 获取第一个用户作为默认用户，或者创建一个系统用户
    try:
        default_user = User.objects.first()
        if default_user:
            # 为所有没有user的exam设置默认用户
            Exam.objects.filter(user__isnull=True).update(user=default_user)
    except Exception:
        # 如果没有用户，跳过这个步骤
        pass


def reverse_set_default_user(apps, schema_editor):
    """回滚操作 - 将user字段设为null"""
    Exam = apps.get_model('exams', 'Exam')
    Exam.objects.all().update(user=None)


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_add_user_and_participants'),
        ('accounts', '0001_initial'),  # 确保accounts应用已经迁移
    ]

    operations = [
        migrations.RunPython(set_default_user_for_exams, reverse_set_default_user),
        
        # 现在可以安全地将user字段设为非空
        migrations.AlterField(
            model_name='exam',
            name='user',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                related_name='exams',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
