# Generated by Django 5.2.5 on 2025-01-27 00:08
# 修复现有数据，确保exam_time字段兼容性

from django.db import migrations, connection


def fix_existing_exam_data(apps, schema_editor):
    """修复现有的exam数据"""
    cursor = connection.cursor()
    
    # 检查是否有exam记录缺少user_id
    cursor.execute("""
        SELECT COUNT(*) FROM exams_exam WHERE user_id IS NULL;
    """)
    null_user_count = cursor.fetchone()[0]
    
    if null_user_count > 0:
        # 如果有记录缺少user_id，需要设置默认值或删除这些记录
        # 这里我们选择删除这些无效记录
        cursor.execute("""
            DELETE FROM exams_exam WHERE user_id IS NULL;
        """)
        print(f"已删除 {null_user_count} 个缺少用户关联的考试记录")


def reverse_fix_data(apps, schema_editor):
    """回滚操作"""
    # 这个操作不可逆，因为我们删除了无效数据
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_add_postgresql_fields'),
    ]

    operations = [
        migrations.RunPython(fix_existing_exam_data, reverse_fix_data),
        
        # 确保user字段不能为空
        migrations.RunSQL(
            "ALTER TABLE exams_exam ALTER COLUMN user_id SET NOT NULL;",
            reverse_sql="ALTER TABLE exams_exam ALTER COLUMN user_id DROP NOT NULL;"
        ),
    ]
