# Generated by Django 5.2.5 on 2025-09-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_simplify_exam_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_time',
            field=models.DateField(verbose_name='考试日期'),
        ),
    ]