# Generated by Django 5.2.5 on 2025-08-24 01:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='书名', max_length=200)),
                ('author', models.CharField(help_text='作者', max_length=100)),
                ('isbn', models.CharField(blank=True, help_text='ISBN编号', max_length=20)),
                ('publisher', models.CharField(blank=True, help_text='出版社', max_length=100)),
                ('publish_year', models.PositiveIntegerField(blank=True, help_text='出版年份', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)])),
                ('category', models.CharField(choices=[('literature', '文学'), ('science', '科学'), ('technology', '技术'), ('history', '历史'), ('philosophy', '哲学'), ('art', '艺术'), ('education', '教育'), ('children', '儿童'), ('other', '其他')], default='other', help_text='书籍分类', max_length=20)),
                ('condition', models.CharField(choices=[('new', '全新'), ('like-new', '几乎全新'), ('good', '良好'), ('fair', '一般'), ('poor', '较差')], default='good', help_text='书籍品相', max_length=20)),
                ('status', models.CharField(choices=[('available', '可售'), ('sold', '已售出'), ('reserved', '已预订'), ('removed', '已下架')], default='available', help_text='书籍状态', max_length=20)),
                ('description', models.TextField(help_text='书籍描述')),
                ('price', models.DecimalField(decimal_places=2, help_text='售价', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='原价', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('location', models.CharField(blank=True, help_text='所在地区', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list, help_text='标签列表')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(help_text='卖家', on_delete=django.db.models.deletion.CASCADE, related_name='books_for_sale', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
                'db_table': 'books_book',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='书籍图片', upload_to='books/')),
                ('is_cover', models.BooleanField(default=False, help_text='是否为封面图')),
                ('order', models.PositiveIntegerField(default=0, help_text='显示顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='books.book')),
            ],
            options={
                'verbose_name': '书籍图片',
                'verbose_name_plural': '书籍图片',
                'db_table': 'books_book_image',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='交易金额', max_digits=8)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('confirmed', '已确认'), ('paid', '已付款'), ('shipped', '已发货'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', help_text='订单状态', max_length=20)),
                ('message', models.TextField(blank=True, help_text='买家留言')),
                ('payment_method', models.CharField(blank=True, choices=[('wechat', '微信支付'), ('alipay', '支付宝'), ('cash', '现金交易'), ('bank-transfer', '银行转账')], help_text='支付方式', max_length=20)),
                ('buyer_contact', models.CharField(help_text='买家联系方式', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='books.book')),
                ('buyer', models.ForeignKey(help_text='买家', on_delete=django.db.models.deletion.CASCADE, related_name='book_orders', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(help_text='卖家', on_delete=django.db.models.deletion.CASCADE, related_name='book_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '书籍订单',
                'verbose_name_plural': '书籍订单',
                'db_table': 'books_book_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='收件人姓名', max_length=50)),
                ('phone', models.CharField(help_text='手机号码', max_length=20)),
                ('province', models.CharField(help_text='省份', max_length=20)),
                ('city', models.CharField(help_text='城市', max_length=20)),
                ('district', models.CharField(help_text='区县', max_length=20)),
                ('address', models.CharField(help_text='详细地址', max_length=200)),
                ('zip_code', models.CharField(blank=True, help_text='邮政编码', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='books.bookorder')),
            ],
            options={
                'verbose_name': '送货地址',
                'verbose_name_plural': '送货地址',
                'db_table': 'books_shipping_address',
            },
        ),
    ]
