# Generated by Django 5.2.5 on 2025-08-24 02:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['category', 'condition'], name='books_book_categor_59e1a0_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['price'], name='books_book_price_9cc12f_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['status'], name='books_book_status_ea5e47_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['seller', 'status'], name='books_book_seller__d8dbc7_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['created_at'], name='books_book_created_572b47_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['location'], name='books_book_locatio_cf63fa_idx'),
        ),
        migrations.AddIndex(
            model_name='bookorder',
            index=models.Index(fields=['status'], name='books_book__status_6a8fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='bookorder',
            index=models.Index(fields=['buyer', 'status'], name='books_book__buyer_i_e424ad_idx'),
        ),
        migrations.AddIndex(
            model_name='bookorder',
            index=models.Index(fields=['seller', 'status'], name='books_book__seller__85acd2_idx'),
        ),
        migrations.AddIndex(
            model_name='bookorder',
            index=models.Index(fields=['created_at'], name='books_book__created_9ccbc3_idx'),
        ),
        migrations.AddIndex(
            model_name='bookorder',
            index=models.Index(fields=['book', 'status'], name='books_book__book_id_86c9fe_idx'),
        ),
    ]
